state: classic

agents:
  - rmaxq
  - ramdp


episodes: 10
max_steps: 2000
trials: 2
gamma: 0.95

stochastic:
  seed: 89273911200
  correct_move: 0.8
  fickle: 0.05
  random_start: true

planning:
  rollouts: 1000

rmax:
  vmax: 20
  threshold: 5
  max_delta: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdpVrmaxqn-classic-jwtest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    width: 5
    height: 5
