state: classic-2passengers

agents:
  - ramdp

episodes: 100
max_steps: 2000
trials: 1
gamma: 0.99

stochastic:
  seed: 64753211
  correct_move: 0.85
  fickle: 0.40
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 5
  max_delta: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: false

output:
  csv:
    enabled: true
    output: results/ramdp-classic-2-slippery-fickle.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
