state: classic-2passengers

agents:
  - palmExpert

episodes: 100
max_steps: 2000
trials: 1
gamma: 0.99

stochastic:
  seed: 7543221
  correct_move: 1.0
  fickle: 0.333
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 20
  max_delta: 0.0001
  max_iterations_in_model: 100
  use_multitime_model: false

output:
  csv:
    enabled: true
    output: results/pex-classic-2-fickle.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
