domain: !!config.taxi.TaxiConfig
  state: classic-2passengers
  correct_move: 1.0
  fickle: 0.0
  random_start: false

agents:
  - palmExpert

episodes: 100
max_steps: 500
trials: 1
gamma: 0.99

seed: 1232100

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 10
  max_delta: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: true

output:
  csv:
    enabled: true
    output: results/pex-classic-2-ggpp-d2s.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
