state: classic

agents:
  - ramdp

episodes: 200
max_steps: 200
trials: 1
gamma: 0.99

stochastic:
  seed: 1290193
  correct_move: 0.85
  fickle: 0.10
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 20
  threshold: 3
  max_delta: 0.001
  max_delta_in_model: 0.001
  max_iterations_in_model: 1000

output:
  csv:
    enabled: true
    output: results/ramdp-jwtest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
