state: tiny-2passengers

agents:
  - rmaxq

episodes: 1000
max_steps: 10000
trials: 1
gamma: 0.99

stochastic:
  seed: 62665532323
  correct_move: 1.0
  fickle: 0.0
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 1
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true

output:
  csv:
    enabled: true
    output: results/ramdp-jwtest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
