state: steptest

agents:
  - palmExpert

episodes: 300
max_steps: 1000
trials: 1
gamma: 0.99

stochastic:
  seed: 4917419
  correct_move: 0.5
  fickle: 0.0
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 5
  max_delta: 0.00001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true

output:
  csv:
    enabled: true
    output: results/pex-classic.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5
    
