#state: steptest-2passengers
state: steptest-2passengers

agents:
  - palmExpert
  - expectedStepsTest

episodes: 1000
max_steps: 1000
trials: 5
gamma: 0.90

stochastic:
  seed: 4917419
  correct_move: 1.0
  fickle: 0.0
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 20
  max_delta: 0.0000000001
  max_iterations_in_model: 1000
  use_multitime_model: true

output:
  csv:
    enabled: true
    output: results/pex-classic.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
