state: tiny

agents:
  - ramdp
  - rmaxq

episodes: 30
max_steps: 2000
trials: 20
gamma: 0.9

stochastic:
  correct_move: 1
  fickle: 0
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 20
  threshold: 5
  max_delta: 0.01

output:
  csv:
    enabled: true
    output: results/ramdp-tiny.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 5
    height: 5
