domain: !!edu.umbc.cs.maple.config.taxi.TaxiConfig
  state: medium
  correct_move: 1.0
  fickle: 0.00

agents:
#  - rmaxqExpert
#  - rmaxqHierGen
  - palmExpert
#  - palmExpertWithNavGiven
#  - palmHierGen
#  - kappaExpert
#  - kappaHierGen
#  - qLearning

seed: 555666777 # 6674931
episodes: 50
max_steps: 100000
trials: 10
gamma: 0.99

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 10.0
  threshold: 5
  max_delta: 0.0000001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: false
  wait_for_children: false
  use_model_sharing: true


output:
  csv:
    enabled: true
    output: results/classic.csv

  chart:
    enabled: true

    width: 500
    height: 230
    columns: 2
    max_height: 693
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5
    

