domain: !!edu.umbc.cs.maple.config.taxi.TaxiConfig
  state: tiny
  domainGenerator: !!edu.umbc.cs.maple.taxi.Taxi
    correctMoveProbability: 1.0
    fickleProbability: 0.0
    tf: !!edu.umbc.cs.maple.taxi.TaxiTerminalFunction {}
    rf: !!edu.umbc.cs.maple.taxi.TaxiRewardFunction {}

goal: !!edu.umbc.cs.maple.taxi.TaxiGoal {}

agents:
  palm: {taxi-expert}

seed: 77665544
episodes: 100
max_steps: 100000
trials: 1
gamma: 0.95

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 10.0
  threshold: 10
  max_delta: 0.0000001
  max_delta_rmaxq: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: true
  use_model_sharing: true


output:
  csv:
    enabled: true
    output: results/pex-classic-fickle.csv

  chart:
    enabled: true

    width: 500
    height: 230
    columns: 2
    max_height: 693
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5



