seed: 32552

state: threeRooms

numBlocks: 2

minX: 0
minY: 0
maxX: 5
maxY: 5

rewardGoal: 1.0
rewardBase: -0.001
rewardNoop: -0.001
rewardPull: 0.0

agents:
  - ramdp

episodes: 100
max_steps: 1000
trials: 10
gamma: 0.95

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 0.8
  threshold: 1
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-3rooms-2block.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 300
    height: 300
