seed: 3255211111

state: threeRooms

numBlocks: 1

minX: 0
minY: 0
maxX: 5
maxY: 5

rewardGoal: 1.0
rewardBase: -0.001
rewardNoop: -0.001
rewardPull: 0.0

agents:
  - rmaxq
  - ramdp

episodes: 100
max_steps: 200
trials: 2
gamma: 0.95

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 0.5
  threshold: 1
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-rmaxqTest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 420
    height: 300
