seed: 325523

state: threeRooms

numBlocks: 2

minX: 0
minY: 0
maxX: 9
maxY: 9

rewardGoal: 1.0
rewardBase: 0.0
rewardNoop: 0.0
rewardPull: 0.0

agents:
  - ramdp

episodes: 300
max_steps: 10000
trials: 1
gamma: 0.99

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 2
  max_delta: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: true

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-3rooms-2block.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 300
    height: 300
