domain: !!config.cleanup.CleanupConfig
    state: threeRooms
    num_blocks: 2
    minX: 0
    minY: 0
    maxX: 5
    maxY: 5
    rewardGoal: 1.0
    rewardBase: 0.0
    rewardNoop: 0.0
    rewardPull: 0.0
    
seed: 325523

agents:
  - palmExpert

episodes: 300
max_steps: 100
trials: 1
gamma: 0.99

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 2
  max_delta: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: true

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-3rooms-2block.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
