seed: 32552

state: threeRooms

numBlocks: 2

minX: 0
minY: 0
maxX: 5
maxY: 5

rewardGoal: 500.0
rewardBase: -1.0
rewardNoop: -1.0
rewardPull: 0.0

agents:
  - rmaxq
  - ramdp

episodes: 50
max_steps: 500
trials: 4
gamma: 0.95

planning:
  rollouts: 10000

rmax:
  vmax: 999
  threshold: 3
  max_delta: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-rmaxqTest.csv

  chart:
    enabled: true

    width: 300
    height: 200
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    width: 300
    height: 300
