seed: 325521

state: twoRooms

numBlocks: 2

minX: 0
minY: 0
maxX: 7
maxY: 5

rewardGoal: 500.0
rewardBase: -1.0
rewardNoop: -1.0
rewardPull: 0.0

agents:
  - rmaxq
  - ramdp

episodes: 60
max_steps: 1000
trials: 20
gamma: 0.95

planning:
  rollouts: 10000

rmax:
  vmax: 999
  threshold: 3
  max_delta: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-rmaxqTest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 420
    height: 300
