seed: 325521

state: twoRooms

numBlocks: 1

minX: 0
minY: 0
maxX: 7
maxY: 5

rewardGoal: 1.0
rewardBase: -0.1
rewardNoop: -0.1
rewardPull: 0.0

agents:
  - rmaxq
  - ramdp

episodes: 60
max_steps: 10000
trials: 20
gamma: 0.95

planning:
  rollouts: 10000

rmax:
  vmax: 1.0
  threshold: 1
  max_delta: 0.01
  max_delta_in_model: 0.01

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-rmaxqTest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    width: 420
    height: 300
