seed: 325521

state: twoRooms

numBlocks: 1

minX: 0
minY: 0
maxX: 7
maxY: 5

rewardGoal: 10.0
rewardBase: 0.0
rewardNoop: 0.0
rewardPull: 0.0

agents:
  - rmaxq
  - ramdp

episodes: 100
max_steps: 300
trials: 2
gamma: 0.95

planning:
  rollouts: 1000

rmax:
  vmax: 12.34
  threshold: 2
  max_delta: 0.001
  max_delta_in_model: 0.001

output:
  csv:
    enabled: true
    output: results/ramdp-cleanup-rmaxqTest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 420
    height: 300
