name: expert-baseline
hierarchyConfigMap:
  root:
    children:
      - North_np
      - South_np
      - East_np
      - West_np
      - Pull_np
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.root.CleanupRootGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.root.CleanupRootFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
      tf: *tf
      rf: *rf
      stateClasses:
         - className: agent
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
         - className: block
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
      actions:
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.DirectionActionType
          name: North
          dx: 0
          dy: 1
          parameterOrderGroups:
            - North.P0
            - North.P1
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.DirectionActionType
          name: South
          dx: 0
          dy: -1
          parameterOrderGroups:
            - South.P0
            - South.P1
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.DirectionActionType
          name: East
          dx: 1
          dy: 0
          parameterOrderGroups:
            - East.P0
            - East.P1
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.DirectionActionType
          name: West
          dx: -1
          dy: 0
          parameterOrderGroups:
            - West.P0
            - West.P1
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PullActionType
          name: Pull
          parameterOrderGroups:
            - Pull.P0
            - Pull.P1
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  North:
    children:
     - north_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *tf
       rf: *rf
       stateClasses:
          - className: agent
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
          - className: block
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
           typeName: north
           action: !!burlap.mdp.core.action.SimpleAction
              name: north
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  South:
    children:
     - south_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *tf
       rf: *rf
       stateClasses:
          - className: agent
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
          - className: block
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
           typeName: south
           action: !!burlap.mdp.core.action.SimpleAction
              name: south
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  East:
    children:
     - east_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *tf
       rf: *rf
       stateClasses:
          - className: agent
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
          - className: block
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
           typeName: east
           action: !!burlap.mdp.core.action.SimpleAction
              name: east
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  West:
    children:
     - west_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *tf
       rf: *rf
       stateClasses:
          - className: agent
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
          - className: block
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
           typeName: west
           action: !!burlap.mdp.core.action.SimpleAction
              name: west
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  Pull:
    children:
     - pull_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.simple.PrimitiveShieldFailPF {}
    rf: &rf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *tf
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *tf
       rf: *rf
       stateClasses:
          - className: agent
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
          - className: block
            clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
           typeName: pull
           action: !!burlap.mdp.core.action.SimpleAction
              name: pull
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000