name: expert-moveXY
hierarchyConfigMap:
  root:
    children:
      - pull_p
      - moveAgentXY_np
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &rootTF !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.root.CleanupRootGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.root.CleanupRootFailPF {}
    rf: &rootRF !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *rootTF
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
      tf: *rootTF
      rf: *rootRF
      stateClasses:
        - className: agent
          clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
        - className: block
          clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
        - className: room
          clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupRoom {}
        - className: door
          clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupDoor {}
      actions:
        - !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.move.MoveAgentXYActionType
          name: moveAgentXY
          parameterClasses:
            - x
            - y
          parameterOrderGroup:
            - moveAgentXY.P0
            - moveAgentXY.P1
            - moveAgentXY.P3
        - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
          typeName: pull
          action: !!burlap.mdp.core.action.SimpleAction
            name: pull
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000

  moveAgentXY:
    children:
       - north_p
       - south_p
       - east_p
       - west_p
    stateMapper: !!edu.umbc.cs.maple.hierarchy.framework.IdentityMap {}
    tf: &xyTF !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
      goalPF: &goalPF !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.move.MoveAgentXYGoalPF {}
      failPF: !!edu.umbc.cs.maple.cleanup.hierarchies.tasks.move.MoveAgentXYFailPF {}
    rf: &xyRF !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
      tf: *xyTF
      rewardDefault: 0.0
      rewardNoop: 0.0
    domainGenerator: !!edu.umbc.cs.maple.hierarchy.framework.TaskDomainGenerator
       tf: *xyTF
       rf: *xyRF
       stateClasses:
         - className: agent
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupAgent {}
         - className: block
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupBlock {}
         - className: room
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupRoom {}
         - className: door
           clasz: !!edu.umbc.cs.maple.cleanup.state.CleanupDoor {}
       actions:
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
             typeName: north
             action: !!burlap.mdp.core.action.SimpleAction
                 name: north
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
             typeName: south
             action: !!burlap.mdp.core.action.SimpleAction
                 name: south
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
             typeName: east
             action: !!burlap.mdp.core.action.SimpleAction
                 name: east
         - !!edu.umbc.cs.maple.hierarchy.framework.UniversalActionTypeBean
             typeName: west
             action: !!burlap.mdp.core.action.SimpleAction
                 name: west
    solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
      maxDelta: 0.0001
      maxIterations: 1000
