baseDomainGenerator: &baseDomain !!taxi.Taxi
  fickle: false
  fickleProb: 0.0
  moveDynamics: 1.0

hierarchyConfigMap:
  - root:
      children:
        - task5_np
        - task7_np
        - putdown_p

      domainGenerator: *baseDomain

      stateMapper: !!taxi.hiergen.root.state.HierGenRootStateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.hiergen.functions.HierGenRootCompleted
        failPF: !!taxi.hiergen.functions.FailureFunction

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000

  - task7:
      children:
        - task5_np
        - pickup_p

      domainGenerator: *baseDomain

      stateMapper: !!taxi.hiergen.task7.state.Task7StateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.hiergen.functions.HierGenTask7Completed
        failPF: !!taxi.hiergen.functions.FailureFunction

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000

  - task5:
      children:
        - north_p
        - south_p
        - east_p
        - west_p

      domainGenerator: *baseDomain

      stateMapper: !!taxi.hiergen.task5.state.Task5StateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.hiergen.functions.HierGenTask5Completed
        failPF: !!taxi.hiergen.functions.FailureFunction

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000