baseDomainGenerator: !!taxi.Taxi
  fickle: false
  fickleProb: 0.0
  moveDynamics: 1.0

hierarchyConfigMap:
  - root:
      children:
        - get_np
        - set_np

      domainGenerator: !!taxi.hierarchies.tasks.root.TaxiRootDomain

      stateMapper: !!taxi.hierarchies.tasks.root.state.RootStateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.functions.amdp.RootCompletedPF
        failPF: !!taxi.functions.amdp.RootFailurePF

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000

  - get:
      children:
        - nav_np
        - pickup_p

      domainGenerator: !!taxi.hierarchies.tasks.get.TaxiGetDomain

      stateMapper: !!taxi.hierarchies.tasks.get.state.GetStateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.functions.amdp.GetCompletedPF
        failPF: !!taxi.functions.amdp.GetFailurePF

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000

  - put:
      children:
        - nav_np
        - putdown_p

      domainGenerator: !!taxi.hierarchies.tasks.put.TaxiPutDomain

      stateMapper: !!taxi.hierarchies.tasks.put.state.PutStateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.functions.amdp.PutCompletedPF
        failPF: !!taxi.functions.amdp.PutFailurePF

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000
  - nav:
      children:
        - north_p
        - south_p
        - east_p
        - west_p

      domainGenerator: !!taxi.hierarchies.tasks.nav.TaxiNavDomain

      stateMapper: !!taxi.hierarchies.tasks.nav.state.NavStateMapper

      tf: &tf !!hierarchy.framework.GoalFailTF
        goalPF: !!taxi.functions.amdp.NavCompletedPF
        failPF: !!taxi.functions.amdp.NavFailurePF

      rf: !!hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0

      solver: !!ValueIterationMultiStepConfig
        maxDelta: 0.0001
        maxIterations: 1000