domain: !!edu.umbc.cs.maple.config.cleanup.CleanupConfig
  state: twoRooms
  num_blocks: 2
  minX: 0
  minY: 0
  maxX: 7
  maxY: 5
  rewardGoal: 1.0
  rewardBase: 0.0
  rewardNoop: 0.0
  rewardPull: 0.0
    
goal: !!edu.umbc.cs.maple.cleanup.CleanupGoal
  goalDescriptions:
    - pf: !!edu.umbc.cs.maple.cleanup.pfs.BlockInRoomPF {}
      params:
       - block0
       - room1

agents:
  cross: {cleanup-jw}
  palm:  {cleanup-jw}

seed: 555543
episodes: 100
max_steps: 10000
trials: 1
gamma: 0.99

identifier_independent: false
planning:
  rollouts: 10000

rmax:
  vmax: 10.0
  threshold: 5
  max_delta: 0.000001
  max_delta_rmaxq: 0.000001
  max_iterations_in_model: 1000
  use_multitime_model: true
  use_model_sharing: false

output:
  csv:
    enabled: true
    output: results/palm-cleanup-jwtest.csv

  chart:
    enabled: true

    width: 400
    height: 200
    columns: 2
    max_height: 650
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 7
    height: 5
