state: classic

agents:
  - ramdp

episodes: 100
max_steps: 2000
trials: 2
gamma: 0.95

stochastic:
  seed: 2320942930
  correct_move: 0.8
  fickle: 0.05
  random_start: false

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 20
  max_delta: 0.01
  max_iterations_in_model: 100

output:
  csv:
    enabled: true
    output: results/ramdpsmall.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    width: 5
    height: 5
