state: classic

agents:
  - ramdp

episodes: 10
max_steps: 2000
trials: 2
gamma: 0.95

stochastic:
  seed: 4242419992
  correct_move: 1.0
  fickle: 0.0
  random_start: true

planning:
  rollouts: 1000

rmax:
  vmax: 20
  threshold: 2
  max_delta: 0.00001
  max_iterations_in_model: 1000

output:
  csv:
    enabled: true
    output: results/classic-jwtest.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    width: 5
    height: 5
