state: classic

agents:
  - ramdp
  - rmaxq

episodes: 30
max_steps: 2000
trials: 20
gamma: 0.9

stochastic:
  correct_move: 0.8
  fickle: 0.225
  random_start: false

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 20
  threshold: 5
  max_delta: 0.01
  max_iterations_in_model: 1000

output:
  csv:
    enabled: true
    output: results/ramdp-classic-fickle.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 1000
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    width: 5
    height: 5
